Update readme.md
joewadcan/FirstPullRequest pull request #685
Opened 2023-02-16 05:10 UTC by dbadih

## Objective

New update for name

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 
@jahnavishah121-coder

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

2023-02-16 06:32 UTC, aparnachaganty requested changes
@dbadih  - Please update the pull request with your username. Currently the username is missing.

2023-02-17 05:03 UTC, dbadih commented on 2023_Spring/readme.md
> +- [X] Badih, Dalia (@dbadih) :D
username added

2023-02-17 05:04 UTC, dbadih commented
@aparnachaganty username added

2023-02-28 18:43 UTC, aparnachaganty approved these changes

2023-02-28 18:44 UTC, merged