Update readme.md
joewadcan/FirstPullRequest pull request #690
Opened 2023-02-16 05:12 UTC by spg222

## Objective

_Updated readme for Supriya_

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

2023-02-16 05:17 UTC, smallyn9 reviewed
You missed the @ mention!!!!

2023-02-16 06:34 UTC, aparnachaganty approved these changes

2023-02-16 06:35 UTC, aparnachaganty requested changes
@spg222  : The PR currently shows that you've made duplicate changes. Click on "resolve conflicts" on the PR page and remove duplicates. I'll be able to merge the changes right after that.

2023-02-23 02:25 UTC, aparnachaganty approved these changes

2023-02-23 02:26 UTC, merged